### ISSUE TITLE
More notes on Kirkstone compatibility

### ISSUE THREAD

**Issue by bkauler** [OldManYellsAtCloud/meta-browser#49]
This is a follow-on from https://github.com/OldManYellsAtCloud/meta-browser/issues/30

I'm running EasyOS and successfully compiled Firefox 119.0 in OE Kirkstone.

In fact, EasyOS itself is built entirely from packages compiled in OE. My build system is here:

https://github.com/bkauler/oe-qky-kirkstone

...it builds everything, including LibreOffice, Chromium ...and now Firefox.

However, there were problems. 'nss 3.93' build failed, so I changed to internal nss and nspr. This change was made in the setup script:

https://github.com/bkauler/oe-qky-kirkstone/blob/main/create-oe-quirky-ff

...and you will also see in there, changed rust to 1.72.0

I created firefox_%.bbappend and changed to some system libraries. 'icu' in kirkstone is too old, so got it out of openembedded-core master:

https://github.com/bkauler/oe-qky-kirkstone/tree/main/quirky/meta-quirky/recipes-support/icu

Here is firefox_%.bbappend:

https://github.com/bkauler/oe-qky-kirkstone/blob/main/quirky/meta-quirky/recipes-browser/firefox/firefox_%25.bbappend

...I tried to get it to build without requiring nasm-native, but no go. Note, I am compiling on x86_64 host system, for a x86_64 nocona target -- "nocona" is the very first 64-bit cpu that Intel released.

Finished the entire build this morning, it took 1 day (24 hours) and 18 hours!

**Comment by bkauler** [comment]
And for the record, this is the layers:

https://github.com/bkauler/oe-qky-kirkstone/blob/main/quirky/build-amd64-ff/conf/bblayers.conf

And local.conf:

https://github.com/bkauler/oe-qky-kirkstone/blob/main/quirky/build-amd64-ff/conf/local.conf

**Comment by OldManYellsAtCloud** [comment]
Thank you so much for taking the time to post this write up.

  > 'nss 3.93' build failed

Hmmm, that's weird. I have updated it to 3.94 a day or two ago, but still, neither versions' compilation should have failed... but regardless, now I see a bug. I only build my systems for ARM and RISC-V, not for x86/64. The vendored nss mostly is meant for systems without existing/working hw-crypto engine (like armv7, or risc-v until about a few days ago...). Going to tweak that, and possibly add an x86/64 build also on my local box.

  > changed rust to 1.72.0
  
I trust that bumping rust shouldn't cause harm. If I recall correctly, Firefox should be happy with anything over 1.60(ish).

  > nasm-native
  > icu
  
Right, I see that you added some comments in your bbappend, that it is required for some extra codecs. Will check if it makes sense to set something similar as default.

**Comment by OldManYellsAtCloud** [comment]
I got some time to get back on this.

- I have added `nasm-native` as a dependency for x86 and x86-64 arch's, it is a specific requirement for these platforms.
- Now `--with-system-nss` is a requirement only for arm and aarch64 arch's, without crypgraphic hw support. This support is required on x86-64 also, but it looks like that it has more common support even on older CPUs (I also managed to build FF using your machine config, without `--with-system-nss`). Will handle CPU-exceptions as they pop up, if there will be any.
- I have fixed nss-3.93/3.94 compilation (though it shouldn't build at all for your config, in theory)

I am testing currently the above changes to see if they compile for all my configs, I expect them to merge soon to master.

Regarding `icu`: what is the reason for using the one shipped with OE instead of the FF's built in one? Asking mostly to see if it would make sense to do the same by default.

**Comment by bkauler** [comment]
Great to see what you are doing for FF on x86_64!

The reason I want to use system icu is because icu is very big. It is used by other apps in EasyOS, so it saves space if they all use the same icu.  I did a "du -m usr/lib" in the expanded icu package (libs are stripped), got 36MB.

So I guess it depends on the situation. If you are building an embedded system with hardly anything else except FF then using its internal icu would be appropriate probably.

Maybe it could be a conditional "PACKAGECONFIG[icu]" entry in the recipe, defaulting to internal.

**Comment by OldManYellsAtCloud** [comment]
I see... well, adding a simple PACKAGECONFIG knob won't hurt. But now I'm thinking that instead of adding just `icu` randomly, maybe I could add a PACKAGECONFIG option for all `--with-system-*` options, for consistency. I think I will look into that.

**Comment by OldManYellsAtCloud** [comment]
New PACKAGECONFIG options have been added.
